<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'sword',
                'description' => 'Melee weapon',
                'price' => '1',
                'stock' => '10',
                'category' => 'weapon',
            ],
            [
                'name' => 'shield',
                'description' => 'Protects you in battle',
                'price' => '2',
                'stock' => '10',
                'category' => 'armor',
            ],
            [
                'name' => 'health potion',
                'description' => 'Restores a moderate amount of health',
                'price' => '5',
                'stock' => '15',
                'category' => 'consumable',
            ],
            [
                'name' => 'bow',
                'description' => 'Ranged weapon',
                'price' => '3',
                'stock' => '10',
                'category' => 'weapon',
            ],
            [
                'name' => 'spell book',
                'description' => 'Contains powerful spells',
                'price' => '10',
                'stock' => '10',
                'category' => 'magic',
            ],
            [
                'name' => 'mana potion',
                'description' => 'Restores a moderate amount of mana',
                'price' => '8',
                'stock' => '20',
                'category' => 'consumable',
            ],
            [
                'name' => 'greatsword',
                'description' => 'Massive two-handed sword',
                'price' => '15',
                'stock' => '5',
                'category' => 'weapon',
            ],
            [
                'name' => 'chainmail',
                'description' => 'Flexible armor made of interlocking metal rings',
                'price' => '20',
                'stock' => '7',
                'category' => 'armor',
            ],
            [
                'name' => 'magic wand',
                'description' => 'Focuses magical energy for spells',
                'price' => '12',
                'stock' => '8',
                'category' => 'magic',
            ],
            [
                'name' => 'poison vial',
                'description' => 'Deadly substance that can be applied to weapons',
                'price' => '6',
                'stock' => '12',
                'category' => 'consumable',
            ],
            [
                'name' => 'elixir of strength',
                'description' => 'Temporarily increases physical strength',
                'price' => '7',
                'stock' => '10',
                'category' => 'consumable',
            ],
            [
                'name' => 'enchanted cloak',
                'description' => 'Grants invisibility to the wearer',
                'price' => '25',
                'stock' => '3',
                'category' => 'armor',
            ],
            [
                'name' => 'fireball scroll',
                'description' => 'Unleashes a powerful fireball spell',
                'price' => '18',
                'stock' => '5',
                'category' => 'magic',
            ],
            [
                'name' => 'thunderbolt staff',
                'description' => 'Channels lightning magic for devastating attacks',
                'price' => '30',
                'stock' => '3',
                'category' => 'magic',
            ],
            [
                'name' => 'throwing knives',
                'description' => 'Small, sharp knives for ranged attacks',
                'price' => '4',
                'stock' => '15',
                'category' => 'weapon',
            ],
            [
                'name' => 'potion of agility',
                'description' => 'Increases speed and agility for a short time',
                'price' => '10',
                'stock' => '8',
                'category' => 'consumable',
            ],
            [
                'name' => 'amulet of protection',
                'description' => 'Provides magical protection against attacks',
                'price' => '35',
                'stock' => '5',
                'category' => 'armor',
            ],
            [
                'name' => 'flaming sword',
                'description' => 'A sword enchanted with fire, dealing additional burning damage',
                'price' => '25',
                'stock' => '7',
                'category' => 'weapon',
            ],
            [
                'name' => 'frost staff',
                'description' => 'Channels ice magic for freezing attacks',
                'price' => '28',
                'stock' => '6',
                'category' => 'magic',
            ],
            [
                'name' => 'teleportation scroll',
                'description' => 'Allows the user to teleport to a predetermined location',
                'price' => '40',
                'stock' => '3',
                'category' => 'magic',
            ],
            [
                'name' => 'elixir of invulnerability',
                'description' => 'Grants temporary invulnerability to all damage',
                'price' => '50',
                'stock' => '3',
                'category' => 'consumable',
            ],
            [
                'name' => 'dagger of venom',
                'description' => 'A dagger coated with deadly poison',
                'price' => '15',
                'stock' => '10',
                'category' => 'weapon',
            ],
            [
                'name' => 'robes of the archmage',
                'description' => 'Robes imbued with powerful magical energy, enhancing spellcasting',
                'price' => '45',
                'stock' => '4',
                'category' => 'armor',
            ],
            [
                'name' => 'vial of holy water',
                'description' => 'Blessed water capable of repelling evil forces',
                'price' => '20',
                'stock' => '12',
                'category' => 'consumable',
            ],
            [
                'name' => 'whispering bow',
                'description' => 'A bow that shoots arrows silently, perfect for stealthy attacks',
                'price' => '32',
                'stock' => '5',
                'category' => 'weapon',
            ],
            [
                'name' => 'staff of rejuvenation',
                'description' => 'Restores health and mana to allies in a radius',
                'price' => '55',
                'stock' => '2',
                'category' => 'magic',
            ],
            [
                'name' => 'scroll of summoning',
                'description' => 'Summons a powerful ally to aid in battle',
                'price' => '60',
                'stock' => '2',
                'category' => 'magic',
            ],
            [
                'name' => 'potion of flight',
                'description' => 'Grants the ability to fly for a limited time',
                'price' => '30',
                'stock' => '8',
                'category' => 'consumable',
            ],
            [
                'name' => 'adamantine armor',
                'description' => 'Armor forged from the strongest metal, providing unparalleled protection',
                'price' => '70',
                'stock' => '3',
                'category' => 'armor',
            ],
            [
                'name' => 'blade of chaos',
                'description' => 'A chaotic weapon capable of unpredictable and devastating attacks',
                'price' => '40',
                'stock' => '6',
                'category' => 'weapon',
            ],
            [
                'name' => 'orb of enlightenment',
                'description' => 'Grants knowledge and insight to the user',
                'price' => '50',
                'stock' => '4',
                'category' => 'magic',
            ],
            [
                'name' => 'potion of invisibility',
                'description' => 'Makes the user invisible for a limited duration',
                'price' => '35',
                'stock' => '6',
                'category' => 'consumable',
            ],
            [
                'name' => 'Dragonfire potion',
                'description' => 'Inflicts heavy fire damage to the target',
                'price' => '75',
                'stock' => '4',
                'category' => 'consumable',
            ],
            [
                'name' => 'Scepter of the Elements',
                'description' => 'Harnesses the power of all four elements for devastating attacks',
                'price' => '90',
                'stock' => '2',
                'category' => 'magic',
            ],
            [
                'name' => 'Cloak of Shadows',
                'description' => 'Grants the wearer near-invisibility in dark environments',
                'price' => '65',
                'stock' => '3',
                'category' => 'armor',
            ],
            [
                'name' => 'Soul Reaper Scythe',
                'description' => 'Steals the life force from enemies upon each strike',
                'price' => '80',
                'stock' => '5',
                'category' => 'weapon',
            ],
            [
                'name' => 'Potion of Eternal Youth',
                'description' => 'Grants eternal youth to the drinker',
                'price' => '150',
                'stock' => '0',
                'category' => 'consumable',
            ],
            [
                'name' => 'Ring of Time Manipulation',
                'description' => 'Allows the wearer to manipulate time in a limited capacity',
                'price' => '200',
                'stock' => '1',
                'category' => 'magic',
            ],
            [
                'name' => 'Titanium Plate Armor',
                'description' => 'Impossibly strong armor made of titanium',
                'price' => '120',
                'stock' => '3',
                'category' => 'armor',
            ],
            [
                'name' => 'Vorpal Blade',
                'description' => 'A weapon capable of severing limbs with a single strike',
                'price' => '100',
                'stock' => '4',
                'category' => 'weapon',
            ],
            [
                'name' => 'Elixir of Omniscience',
                'description' => 'Grants the drinker all knowledge in the universe temporarily',
                'price' => '250',
                'stock' => '0',
                'category' => 'consumable',
            ],
            [
                'name' => 'Staff of the Celestials',
                'description' => 'Channel the power of the celestial beings to smite enemies',
                'price' => '300',
                'stock' => '1',
                'category' => 'magic',
            ],
            [
                'name' => 'Cape of the Void',
                'description' => 'Allows the wearer to traverse through the void unharmed',
                'price' => '180',
                'stock' => '2',
                'category' => 'armor',
            ],
            [
                'name' => 'Axe of Ragnarok',
                'description' => 'A weapon said to bring about the end of times with each swing',
                'price' => '280',
                'stock' => '1',
                'category' => 'weapon',
            ],
            [
                'name' => 'Potion of Levitation',
                'description' => 'Grants the ability to levitate off the ground for a limited time',
                'price' => '70',
                'stock' => '5',
                'category' => 'consumable',
            ],
            [
                'name' => 'Orb of Destruction',
                'description' => 'Unleashes a devastating explosion upon activation',
                'price' => '220',
                'stock' => '0',
                'category' => 'magic',
            ],
            [
                'name' => 'Crystal Shield',
                'description' => 'A shield made of enchanted crystal, nearly impenetrable',
                'price' => '160',
                'stock' => '2',
                'category' => 'armor',
            ],
            [
                'name' => 'Sword of Justice',
                'description' => 'Strikes fear into the hearts of evildoers, delivering swift justice',
                'price' => '140',
                'stock' => '3',
                'category' => 'weapon',
            ],
            [
                'name' => 'Zephyr Blade',
                'description' => 'A blade imbued with the essence of the wind, swift and deadly',
                'price' => '110',
                'stock' => '4',
                'category' => 'weapon',
            ],
            [
                'name' => 'Xenon Crystal',
                'description' => 'A crystal that emits a strange, otherworldly glow',
                'price' => '95',
                'stock' => '3',
                'category' => 'magic',
            ],
            [
                'name' => 'Quicksilver Boots',
                'description' => 'Boots that enhance the wearer\'s speed and agility',
                'price' => '85',
                'stock' => '5',
                'category' => 'armor',
            ],
            [
                'name' => 'Vortex Elixir',
                'description' => 'Creates a swirling vortex that sucks enemies in',
                'price' => '120',
                'stock' => '3',
                'category' => 'consumable',
            ],
            [
                'name' => 'Zirconium Staff',
                'description' => 'A staff adorned with zirconium gems, amplifying magic',
                'price' => '130',
                'stock' => '4',
                'category' => 'magic',
            ],
            [
                'name' => 'Xenoblade',
                'description' => 'A blade forged from the rare metal Xenomite, capable of cutting through dimensions',
                'price' => '150',
                'stock' => '2',
                'category' => 'weapon',
            ],
            [
                'name' => 'Zephyr Cloak',
                'description' => 'A cloak that grants the wearer the ability to move like the wind',
                'price' => '140',
                'stock' => '3',
                'category' => 'armor',
            ],
            [
                'name' => 'Quantum Orb',
                'description' => 'An orb that manipulates quantum energy for unpredictable effects',
                'price' => '180',
                'stock' => '2',
                'category' => 'magic',
            ],
            [
                'name' => 'Xenophobe\'s Bane',
                'description' => 'A potion that repels xenophobic creatures',
                'price' => '90',
                'stock' => '5',
                'category' => 'consumable',
            ],
            [
                'name' => 'Zarathustra\'s Gauntlets',
                'description' => 'Gauntlets named after the legendary warrior Zarathustra, granting unmatched strength',
                'price' => '200',
                'stock' => '1',
                'category' => 'armor',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
